### PR TITLE
Dynamic content update

### PR DESCRIPTION
**Pull request by tui-test-staff**
This pull request was created automatically by the TUI electronic learning environment. Please check the changed files thoroughly before merging this pull request.

### CODE REVIEW

**Review by bert-janzwanepol — APPROVED** [review]

**Comment by bert-janzwanepol** [comment]
blah

**Comment by bert-janzwanepol** [comment]
bruh @ysbakker

**Comment by ysbakker** [comment]
@bert-janzwanepol wait what

**Comment by ysbakker** [comment]
Zijn we gehackt?

**Comment by bert-janzwanepol** [comment]
Nee was demo, kon zelf niet mergen

**Pull request closed without merging**
